# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f780664640c5e8a729959a0d10494cd24473e94cd1cb993f91a35f045e35637f5750c96135343c1b0acbca1c96cf5bb13961b1d07134d7234232eda4cd86350

test:
  secret_key_base: 111ec4c23237e8acd7288146741d2124ee77017a31f7273511438dfddaf44009e4d1fa2247eeb10f82f31834bddb1c609a6de5327510da0bb398af6960b557b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
